### ISSUE TITLE
Error and Warning in console

### ISSUE THREAD

**Issue by haani104** [boy-techy/react-carousel#1]
![Screenshot 2020-01-02 at 1 02 59 PM](https://user-images.githubusercontent.com/6011865/71656159-453da680-2d60-11ea-9744-73e2cc1091ff.png)

![Screenshot 2020-01-02 at 1 03 10 PM](https://user-images.githubusercontent.com/6011865/71656160-45d63d00-2d60-11ea-826b-8bba33a35de0.png)

Please fix and update the repo

**Comment by boy-techy** [comment]
Hi @haani104,
I have been fixed key issue, but another issue and warnings are coming from "react-responsive-carousel" library. And the issue is still open https://github.com/leandrowd/react-responsive-carousel/issues/322
